### ISSUE TITLE
Geometry turns black at certain angles

### ISSUE THREAD

**Issue by phillippi2** [SIsilicon/Godot-Ocean-Demo#3] opened 2018-06-04 23:04 UTC
![screenshot_20180604_185219](https://user-images.githubusercontent.com/4953001/40945950-faeb20c4-6828-11e8-9e89-6fd634c6beb6.png)
This is showing an issue I'm having with this shader. Any part of the mesh that is at or below a certain angle turns black. The camera angles affects this. Looking straight down at the water, this issue is not apparent.

My system specifications are:
O.S.: Ubuntu 16.04, with Kernel 4.13.
CPU: AMD Ryzen 7 1700
GPU: Radeon RX 570, with the driver included in the Kernel.
Memory: 16GB

**Comment by SIsilicon** [comment] 2018-06-04 23:59
Oh man! That looks awful. Did anything print in the output tab? I have no clue what caused that.

**Comment by phillippi2** [comment] 2018-06-05 00:17
This is what's printed in the output tab
Godot Engine v3.1.dev.custom_build (c) 2007-2018 Juan Linietsky, Ariel Manzur & Godot Contributors.
 scene/2d/canvas_item.cpp:863 - Condition ' !is_inside_tree() ' is true. returned: Rect2()
 scene/gui/control.cpp:2105 - Condition ' !is_inside_tree() ' is true.
 scene/2d/canvas_item.cpp:378 - Condition ' !is_inside_tree() ' is true. returned: get_transform()
 scene/2d/canvas_item.cpp:863 - Condition ' !is_inside_tree() ' is true. returned: Rect2()
 scene/gui/control.cpp:2079 - Condition ' !is_inside_tree() ' is true.
 ./scene/main/node.h:256 - Condition ' !data.tree ' is true. returned: __null
Switch Scene Tab
 scene/resources/texture.cpp:424 - Condition ' !f ' is true. returned: ERR_CANT_OPEN
 Failed loading resource: res://.import/noise_tileable.png-86c7bbd88c367ea4bfd90b5cc356d90b.s3tc.stex
 Failed loading resource: res://noise_tileable.png
 scene/resources/texture.cpp:424 - Condition ' !f ' is true. returned: ERR_CANT_OPEN
 Failed loading resource: res://.import/noise_tileable.png-86c7bbd88c367ea4bfd90b5cc356d90b.s3tc.stex
 Failed loading resource: res://noise_tileable.png
 scene/resources/scene_format_text.cpp:174 - Couldn't load external resource: res://noise_tileable.png

**Comment by SIsilicon** [comment] 2018-06-05 01:41
Looks like you are running a custom build of the currently *unfinished* Godot 3.1. Maybe the problem isn't the addon, but the Godot build. To see if I'm right, try running the same thing on Godot 3.0.2.

**Comment by phillippi2** [comment] 2018-06-05 01:45
I could have sworn that this was the official build from the website...

Anyways, I'll try 3.0.2 when i get off of work

**Comment by phillippi2** [comment] 2018-06-05 13:01
Just tried with 3.0.2. Same problem. Here's the output, if it helps:

odot Engine v3.0.2.stable.official (c) 2007-2018 Juan Linietsky, Ariel Manzur & Godot Contributors.
 scene/2d/canvas_item.cpp:832 - Condition ' !is_inside_tree() ' is true. returned: Rect2()
 scene/gui/control.cpp:2093 - Condition ' !is_inside_tree() ' is true.
 scene/2d/canvas_item.cpp:369 - Condition ' !is_inside_tree() ' is true. returned: get_transform()
 scene/2d/canvas_item.cpp:832 - Condition ' !is_inside_tree() ' is true. returned: Rect2()
 scene/gui/control.cpp:2067 - Condition ' !is_inside_tree() ' is true.
 ./scene/main/node.h:253 - Condition ' !data.tree ' is true. returned: __null
Switch Scene Tab
 scene/resources/texture.cpp:424 - Condition ' !f ' is true. returned: ERR_CANT_OPEN
 Failed loading resource: res://.import/noise_tileable.png-86c7bbd88c367ea4bfd90b5cc356d90b.s3tc.stex
 Failed loading resource: res://noise_tileable.png
 scene/resources/texture.cpp:424 - Condition ' !f ' is true. returned: ERR_CANT_OPEN
 Failed loading resource: res://.import/noise_tileable.png-86c7bbd88c367ea4bfd90b5cc356d90b.s3tc.stex
 Failed loading resource: res://noise_tileable.png
 scene/resources/scene_format_text.cpp:174 - Couldn't load external resource: res://noise_tileable.png

**Comment by SIsilicon** [comment] 2018-06-05 16:08
You know, when I tried to open the project, it did not behave like this. There was no black anywhere. Do you think it's a problem with your graphics driver?

**Comment by SIsilicon** [comment] 2018-06-05 16:10
Now that I mention it, the previews of the scripts in your screen shot are completely blank! It should have some sort of preview.

**Comment by phillippi2** [comment] 2018-06-05 17:21
Those previews have always been blank, since I started trying to use this shader.

It is very likely that the issue is with the driver. There was a similar issue in Alien: Isolation when AMD switched to the new driver stack, called AMDGPU. If that's the case, then upgrading my Kernel may fix this.

**Comment by SIsilicon** [comment] 2018-06-05 18:10
Ok then. Try that.

**Comment by phillippi2** [comment] 2018-06-06 00:03
Confirmed that it's a driver issue. Upgrading Ubuntu's kernel to 4.15 fixes the problem.

**Comment by SIsilicon** [comment] 2018-06-06 00:10
Well I am glad to here that you are able to use it now. Before I close this issue, do you have any suggestions to add to this demo?

**Comment by SIsilicon** [comment] 2018-06-06 00:28
It's half way there. It's should be pretty trivial to add underwater fog effect. I would also need to add internal reflection effect. I'll make it happen. Thanks for the suggestion.

**Closed by SIsilicon** 2018-06-06 00:28 UTC
